/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.23.3
// source: service.proto


/* eslint-disable */
// @ts-nocheck


goog.provide('proto.MachineMapClient');
goog.provide('proto.MachineMapPromiseClient');

goog.require('grpc.web.MethodDescriptor');
goog.require('grpc.web.MethodType');
goog.require('grpc.web.GrpcWebClientBase');
goog.require('grpc.web.AbstractClientBase');
goog.require('grpc.web.ClientReadableStream');
goog.require('grpc.web.RpcError');
goog.require('proto.Machine');
goog.require('proto.MachineStreamRequest');

goog.requireType('grpc.web.ClientOptions');



goog.scope(function() {

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.MachineMapClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.MachineMapPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Machine,
 *   !proto.Machine>}
 */
const methodDescriptor_MachineMap_Pause = new grpc.web.MethodDescriptor(
  '/MachineMap/Pause',
  grpc.web.MethodType.UNARY,
  proto.Machine,
  proto.Machine,
  /**
   * @param {!proto.Machine} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Machine.deserializeBinary
);


/**
 * @param {!proto.Machine} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Machine)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Machine>|undefined}
 *     The XHR Node Readable Stream
 */
proto.MachineMapClient.prototype.pause =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/MachineMap/Pause',
      request,
      metadata || {},
      methodDescriptor_MachineMap_Pause,
      callback);
};


/**
 * @param {!proto.Machine} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Machine>}
 *     Promise that resolves to the response
 */
proto.MachineMapPromiseClient.prototype.pause =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/MachineMap/Pause',
      request,
      metadata || {},
      methodDescriptor_MachineMap_Pause);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Machine,
 *   !proto.Machine>}
 */
const methodDescriptor_MachineMap_UnPause = new grpc.web.MethodDescriptor(
  '/MachineMap/UnPause',
  grpc.web.MethodType.UNARY,
  proto.Machine,
  proto.Machine,
  /**
   * @param {!proto.Machine} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Machine.deserializeBinary
);


/**
 * @param {!proto.Machine} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Machine)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Machine>|undefined}
 *     The XHR Node Readable Stream
 */
proto.MachineMapClient.prototype.unPause =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/MachineMap/UnPause',
      request,
      metadata || {},
      methodDescriptor_MachineMap_UnPause,
      callback);
};


/**
 * @param {!proto.Machine} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Machine>}
 *     Promise that resolves to the response
 */
proto.MachineMapPromiseClient.prototype.unPause =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/MachineMap/UnPause',
      request,
      metadata || {},
      methodDescriptor_MachineMap_UnPause);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.MachineStreamRequest,
 *   !proto.Machine>}
 */
const methodDescriptor_MachineMap_MachineStream = new grpc.web.MethodDescriptor(
  '/MachineMap/MachineStream',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.MachineStreamRequest,
  proto.Machine,
  /**
   * @param {!proto.MachineStreamRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Machine.deserializeBinary
);


/**
 * @param {!proto.MachineStreamRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.Machine>}
 *     The XHR Node Readable Stream
 */
proto.MachineMapClient.prototype.machineStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/MachineMap/MachineStream',
      request,
      metadata || {},
      methodDescriptor_MachineMap_MachineStream);
};


/**
 * @param {!proto.MachineStreamRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.Machine>}
 *     The XHR Node Readable Stream
 */
proto.MachineMapPromiseClient.prototype.machineStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/MachineMap/MachineStream',
      request,
      metadata || {},
      methodDescriptor_MachineMap_MachineStream);
};


}); // goog.scope

